express:
  port: 3000
web_values:
  constants:
    gravity: -0.3
    drag: 0.01
    fps: 60
    bounce_efficiency: 0.75
  variables:
    speed_floor: 70
    speed_max: 400
    dir_floor: 270
    dir_max: 360
  balls:
    radius_floor: 3
    radius_max: 9
    ball_mass_floor: 0.2
    ball_mass_max: 1.2
