express:
  port: 3000
web_values:
  constants:
    gravity: 0.1
    drag: 0.013
    fps: 2
    bounce_efficiency: 1.3
  variables:
    speed_floor: 40
    speed_max: 120
    dir_floor: 0
    dir_max: 360
  balls:
    radius_floor: 3
    radius_max: 9
    ball_mass_floor: 0.2
    ball_mass_max: 1.2
